version: "3.8" # Docker compose dosyasının sürümünü belirler

services:
  backend: # Node.js backend container'ı
    build: . # Bu dizindeki dockerfile'ı işaret eder
    container_name: tour-backend
    ports:
      - 3000:3000
    env_file:
      - .env # .env dosyasındaki tüm env değişkenleri container içine yüklenir
    depends_on:
      - mongo # backend mongo container'ı ayağa kalkmadan başlamaz

  mongo: # Backend'in bağlanacağı DB container'ı
    image: mongo:7 # Hazır mongdb imajını kullan
    container_name: tour-mongo
    restart: always # Eğer container çökerse otomatik restart olur
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db # Veriler kalıcı olsun, container silinse bile kaybolmasın

volumes:
  mongo_data: # MongoDb için kalıcı veri deposu
